name: Deploying Dummy Workflow
on:
  workflow_dispatch:
  push:
    branches: [ master, user/pandeyvinayy/customDeveloperFolio ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered"